### ISSUE TITLE
无法调用谷歌文件原生文件夹

### ISSUE THREAD

**Issue by wendellq89** [tc7326/android11data#1]
型号：huawei mate 30 5G
系统：android 10
报错：Unable to find explicit activity class {com.google.android.documentsui/com.android.documentsui.files.FilesActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by tc7326** [comment]
华为不行吧。Google不是停止对华为的支持了吗。包括应用和google服务 都没法用吧。

**Comment by tc7326** [comment]
在华为上 documents 的包名是 com.android.documentsui 而不是 com.google.android.documentsui 

已更新你试试。
